services:
  # Node.js Backend Service
  - type: web
    name: minute-mate-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_PARENT_PAGE_ID
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Python Whisper API Service
  - type: web
    name: minute-mate-whisper
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python whisper_api.py
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false 